$(function() {
				$("#jieguoDiv").html(localStorage.getItem("resultGrade"));
				var _arr=proposalSchool(localStorage.getItem("resultGrade"));
				if(_arr.length>=1){
					_arr.map(item=>{
						var tr =$("<tr/>");
						var td =$("<td/>");
						td.html(item.school);
						tr.append(td)
						$("#schoolTable").append(tr);
					})
				}
				
				$("#return").click(function() {
					window.history.back(-1);
				})               
				$("#btn").click(function(){
					$("[class=zegaiDiv]").show();
					$('body,html').addClass('add');
				})
				$("[class=zegaiDiv]").click(function(){
					$(this).hide();
					$('body,html').removeClass('add');
				});
})

function proposalSchool(_resultGrade){
	var _school=[
		{	
			result:"6A",
			school:"湖南师大附中"
		},
		{
			result:"6A",
			school:"长沙市一中"
		},{
			result:"6A",
			school:"长郡中学"
		},{
			result:"6A",
			school:"雅礼中学"
		},{
			result:"4A2B",
			school:"明德中学"
		},{
			result:"4A2B",
			school:"周南中学"
		},{
			result:"4A2B",
			school:"长沙市实验中学"
		},{
			result:"5A1B",
			school:"麓山国际实验学校"
		},{
			result:"5A1B",
			school:"南雅中学"
		},{
			result:"3A3B",
			school:"长沙市六中景鹏班"
		},{
			result:"1A5B",
			school:"长沙市六中"
		},{
			result:"2A4B",
			school:"长沙市十一中普通班"
		},{
			result:"2B4C",
			school:"长沙市十一中音乐班"
		},{
			result:"1A4B1C",
			school:"长沙市十一中美术班"
		},{
			result:"6B",
			school:"长沙市十五中"
		},{
			result:"3A3B",
			school:"长沙市二十一中一中合作班"
		},{
			result:"6B",
			school:"长沙市二十一中"
		},{
			result:"2A4B",
			school:"长沙铁路第一中学"
		},{
			result:"6B",
			school:"湖南省地质中学"
		},{
			result:"6B",
			school:"雷锋学校"
		},{
			result:"2A4B",
			school:"长沙外国语学校"
		},{
			result:"3A3B",
			school:"长郡梅溪湖中学"
		},{
			result:"3A3B",
			school:"湖南师大附中梅溪湖中学"
		},{
			result:"3A3B",
			school:"周南梅溪湖中学"
		},{
			result:"3A3B",
			school:"长郡滨江中学"
		},{
			result:"3A3B",
			school:"雅礼洋湖实验中学"
		},{
			result:"3A3B",
			school:"麓山滨江实验学校滨江班"
		},{
			result:"2A4B",
			school:"麓山滨江实验学校"
		},{
			result:"3A3B",
			school:"长郡湘府中学湘府班"
		},{
			result:"1A5B",
			school:"长郡湘府中学"
		},{
			result:"1A4B1C",
			school:"长沙市一中开福中学"
		},{
			result:"2A4B",
			school:"雅礼书院中学雅礼班"
		},{
			result:"1A5B",
			school:"雅礼书院中学"
		},{
			result:"2A3B1C",
			school:"湘一芙蓉中学"
		},{
			result:"2A4B",
			school:"湖南师大附中博才实验中学"
		},{
			result:"2A3B1C",
			school:"麓山外国语实验中学"
		},{
			result:"1A5B",
			school:"长大附中雅礼合作班"
		},{
			result:"1A4B1C",
			school:"长大附中"
		},{
			result:"1A5B",
			school:"周南雨花中学周南合作班"
		},{
			result:"2A3B1C",
			school:"周南雨花中学"
		},{
			result:"1A5B",
			school:"明德雨花实实验中学明德合作班"
		},{
			result:"2A3B1C",
			school:"明德雨花实验中学"
		},{
			result:"2A4B",
			school:"稻田中学"
		},{
			result:"5B1C",
			school:"岳麓实验中学"
		}
	];
	var _arr =[];
	_school.map(item=>{
		if(item.result==_resultGrade){
			_arr.push(item);
		}
	})
	return _arr;
}